/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Boxes({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/OmWvafJUlWoNc0ev/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#74757a']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.77}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[-280, 300, 200]}
          />
          <mesh
            name="Floor"
            geometry={nodes.Floor.geometry}
            material={materials['Floor Material']}
            castShadow
            receiveShadow
            position={[30.98, -10.09, -36]}
            rotation={[-1.58, 0, 0]}
            scale={5}
          />
          <mesh
            name="Cube 5"
            geometry={nodes['Cube 5'].geometry}
            material={materials.Glass}
            castShadow
            receiveShadow
            position={[41.6, 145.43, 69.66]}
            rotation={[-1.59, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 4"
            geometry={nodes['Cube 4'].geometry}
            material={materials.Glass}
            castShadow
            receiveShadow
            position={[41.6, 144.56, 19.85]}
            rotation={[-1.59, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 3"
            geometry={nodes['Cube 3'].geometry}
            material={materials.blue}
            castShadow
            receiveShadow
            position={[41.97, 143.7, -56.17]}
            rotation={[-1.59, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 9"
            geometry={nodes['Cube 9'].geometry}
            material={materials.blue}
            castShadow
            receiveShadow
            position={[225.5, 18.06, 75.96]}
            rotation={[1.55, -1.56, -Math.PI]}
            scale={[1, 0.94, 1]}
          />
          <mesh
            name="Cube 8"
            geometry={nodes['Cube 8'].geometry}
            material={materials['yellow-pink']}
            castShadow
            receiveShadow
            position={[25.96, 68.06, 311.68]}
            rotation={[1.55, -1.56, -Math.PI]}
            scale={[1, 0.94, 1]}
          />
          <mesh
            name="Cube 7"
            geometry={nodes['Cube 7'].geometry}
            material={materials.Glass}
            castShadow
            receiveShadow
            position={[50, 18.43, 312.55]}
            rotation={[-1.59, 0, 0]}
            scale={[1, 0.94, 1]}
          />
          <mesh
            name="Cube 41"
            geometry={nodes['Cube 41'].geometry}
            material={materials.Glass}
            castShadow
            receiveShadow
            position={[41.6, 44.01, 44.5]}
            rotation={[-1.59, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 2"
            geometry={nodes['Cube 2'].geometry}
            material={materials.Glass}
            castShadow
            receiveShadow
            position={[41.6, 44.01, -56.17]}
            rotation={[-1.59, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 42"
            geometry={nodes['Cube 42'].geometry}
            material={materials.Glass}
            castShadow
            receiveShadow
            position={[-60.1, 143.7, 44.5]}
            rotation={[-1.59, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 6"
            geometry={nodes['Cube 6'].geometry}
            material={materials.Glass}
            castShadow
            receiveShadow
            position={[-60.1, 144.34, -80.08]}
            rotation={[-1.59, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 31"
            geometry={nodes['Cube 31'].geometry}
            material={materials['Cube 31 Material']}
            castShadow
            receiveShadow
            position={[-60.1, 145.19, -31.16]}
            rotation={[-1.59, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 43"
            geometry={nodes['Cube 43'].geometry}
            material={materials.blue}
            castShadow
            receiveShadow
            position={[-60.1, 44.01, 44.5]}
            rotation={[-1.59, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.Glass}
            castShadow
            receiveShadow
            position={[-60.1, 44.01, -56.17]}
            rotation={[-1.59, 0, 0]}
            scale={1}
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} position={[7, 3, 7]} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
